// ── Content Templates ────────────────────────────────────────────────────
// Pre-filled defaults for quick content creation by theme

export const CONTENT_TEMPLATES = [
  {
    id: 'roaster-love-carousel',
    name: 'Roaster Love Carousel',
    description: 'Behind-the-scenes roaster feature with carousel images',
    type: 'Roaster Love',
    format: 'Carousel',
    channels: { primary: 'Instagram', secondary: [] },
    stage: 'Idea',
    draftCopy: '',
    notes: 'Angle: What makes this roaster special? Show the process, the people, the place.',
  },
  {
    id: 'coffee-life-photo',
    name: 'Coffee Life Moment',
    description: 'Lifestyle single photo capturing a coffee ritual',
    type: 'Coffee Life',
    format: 'Single Photo',
    channels: { primary: 'Instagram', secondary: [] },
    stage: 'Idea',
    draftCopy: '',
    notes: 'Capture authentic, unposed moments. Natural light preferred.',
  },
  {
    id: 'taste-story-carousel',
    name: 'Taste Story Deep Dive',
    description: 'Educational carousel about a specific coffee origin or process',
    type: 'Taste Story',
    format: 'Carousel',
    channels: { primary: 'Instagram', secondary: ['Email'] },
    stage: 'Idea',
    draftCopy: '',
    notes: 'Structure: Hook slide > origin info > process > tasting notes > CTA',
  },
  {
    id: 'the-build-update',
    name: 'The Build Update',
    description: 'Behind-the-scenes of building tast',
    type: 'The Build',
    format: 'Graphic / Text',
    channels: { primary: 'Instagram', secondary: ['LinkedIn'] },
    stage: 'Idea',
    draftCopy: '',
    notes: 'Be transparent and real. Share wins AND challenges.',
  },
  {
    id: 'community-repost',
    name: 'Community Repost',
    description: 'UGC reshare from the tast community',
    type: 'Community',
    format: 'Repost / UGC',
    channels: { primary: 'Instagram', secondary: [] },
    stage: 'Idea',
    draftCopy: '',
    notes: 'Always credit the original creator. Add a personal note of appreciation.',
  },
  {
    id: 'the-problem-story',
    name: 'The Problem (Story)',
    description: 'IG Story highlighting a problem tast solves',
    type: 'The Problem',
    format: 'Story',
    channels: { primary: 'Instagram', secondary: [] },
    stage: 'Idea',
    draftCopy: '',
    notes: 'Lead with the pain point. Keep it relatable, not preachy.',
  },
  {
    id: 'product-drop-launch',
    name: 'Product Drop Announcement',
    description: 'Multi-channel product launch announcement',
    type: 'Vol. 3 Drop',
    format: 'Carousel',
    channels: { primary: 'Instagram', secondary: ['Email', 'Website'] },
    stage: 'Idea',
    draftCopy: '',
    notes: 'Hype energy. Include product details, pricing, and how to get it.',
  },
  {
    id: 'vol3-tease',
    name: 'Vol. 3 Tease',
    description: 'Cryptic tease for upcoming Vol. 3 release',
    type: 'Vol. 3 Tease',
    format: 'Single Photo',
    channels: { primary: 'Instagram', secondary: ['Instagram Reels'] },
    stage: 'Idea',
    draftCopy: '',
    notes: 'Mystery > clarity. Hint without revealing. Build curiosity.',
  },
  {
    id: 'waitlist-cta',
    name: 'Waitlist CTA',
    description: 'Drive signups to the waitlist',
    type: 'Waitlist',
    format: 'Graphic / Text',
    channels: { primary: 'Instagram', secondary: ['Email'] },
    stage: 'Idea',
    draftCopy: '',
    notes: 'Clear value prop + urgency. Link in bio or swipe-up.',
  },
  {
    id: 'trade-show-recap',
    name: 'Trade Show Recap',
    description: 'Event coverage from a coffee trade show',
    type: 'Trade Show',
    format: 'Carousel',
    channels: { primary: 'Instagram', secondary: ['LinkedIn'] },
    stage: 'Idea',
    draftCopy: '',
    notes: 'Mix of candid shots, booth photos, and key takeaways.',
  },
  {
    id: 'email-newsletter',
    name: 'Email Newsletter',
    description: 'Weekly/monthly email content piece',
    type: 'The Build',
    format: 'Graphic / Text',
    channels: { primary: 'Email', secondary: [] },
    stage: 'Idea',
    draftCopy: '',
    notes: 'Personal, conversational tone. One main story + one CTA.',
  },
  {
    id: 'reels-bts',
    name: 'Reels Behind the Scenes',
    description: 'Quick behind-the-scenes Instagram Reel',
    type: 'Coffee Life',
    format: 'Story',
    channels: { primary: 'Instagram Reels', secondary: ['Instagram'] },
    stage: 'Idea',
    draftCopy: '',
    notes: 'Keep it raw and authentic. 15-30 seconds. Trending audio optional.',
  },
]
